### ISSUE TITLE
Write content for DeFi pulse website

### ISSUE THREAD

**Issue by ghost** [InverseFinance/DeFi-Pulse-Adapters#2]
Include a "What is" description of the project.
Please try to limit this to around 2 - 3 paragraphs (~250 words) and write from the third-person perspective (avoid 'we' or 'our')

Include a "How to use" description of the project.
Please link to your DApp or project and try to keep it brief

example: https://defipulse.com/loopring

**Comment by myfullname295** [comment]
What is Inverse.Finance?

Inverse.finance is a suite of permissionless decentralized finance tools governed by the Inverse DAO, a decentralized autonomous organization running on the Ethereum blockchain. The main Inverse.finance products are Anchor, DOLA, and DCA Vaults. 

Anchor is a money market and synthetic asset protocol enabling capital efficient borrowing & lending. Anchor’s key differentiator is its ability to issue DOLA. 

DOLA is a synthetic stable coin token that tracks the price of $1. DOLA can be minted by using other assets on Anchor as collateral and can itself also be used as collateral to borrow other assets on Anchor. As depositors earn interest on their assets (unlike Maker) and as 1 DOLA always equals $1 of collateral on Anchor (strong peg), DOLA can be a useful stable line of credit for DeFi yield farmers / users and protocol-to-protocol borrowers, especially as the amount of Anchor deposits grows and DOLA becomes more widely adopted.

DCA (Dollar Cost Average) Vaults enable you to invest your tokens into yield bearing strategies while continuously buying the asset of your choice with the proceeds, allowing you to DCA into an asset such as ETH, WBTC or YFI over time. 

The InverseDAO is made up of INV token holders, who govern key aspects of the ecosystem, such as Anchor parameters and product fees. The InverseDAO also controls the treasury that results from various product fees as well as the interest earned from DAI deposits into the ‘Stabilizer’ (a key part of the system where 1 DOLA can be redeemed for 1 DAI and vice versa). A link to the Stabilizer can be found below.

How to Use Inverse.finance:

The best place to start is the main Inverse.finance website or the friendly discord community of INVaders (linked below).  Beyond that, the current ways of using the protocol itself are by lending and borrowing on Anchor, converting DAI to DOLA on the Stabilizer, and / or earning yield on your stable coins through the DCA vaults, and there are more use cases forthcoming. A link to Anchor can be found below, and documentation, as well as walkthroughs and yield farming information, can be found on the Inverse documents portal, which can also be found below.

The Stabilizer: https://inverse.finance/stabilizer

Anchor: https://inverse.finance/banking

DCA vaults: https://inverse.finance/vaults

Documentation: https://docs.inverse.finance/

Discord: https://discord.gg/YpYJC7R5nv

**Comment by ghost** [comment]
Form submitted
